## Sentiment Analysis

In [1]:
import pandas as pd
import numpy as np
 
train = pd.read_csv(r'C:\Users\Ananta Arora\Desktop\Resumes\c.vision\train_2kmZucJ.csv')
test = pd.read_csv(r'C:\Users\Ananta Arora\Desktop\Resumes\c.vision\test_oJQbWVk.csv')

In [2]:
train.shape

(7920, 3)

In [3]:
test.shape

(1953, 2)

In [4]:
test.head(5)

     id                                              tweet
0  7921  I hate the new #iphone upgrade. Won't let me d...
1  7922  currently shitting my fucking pants. #apple #i...
2  7923  I'd like to puts some CD-ROMS on my iPad, is t...
3  7924  My ipod is officially dead. I lost all my pict...
4  7925  Been fighting iTunes all night! I only want th...

In [5]:
train.head(5)

   id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

#### Here, o or 1 means positive or negative

In [6]:
train['label'].value_counts(normalize = True)

0    0.744192
1    0.255808
Name: label, dtype: float64

In [7]:
import seaborn as sns
sns.countplot(x='label',data=train)

### Text-Cleaning
- Remove Punctuation marks
- Remove url links
- Remove numbers
- Converting to lower case

In [8]:
import re
train['clean_tweet'] = train['tweet'].apply(lambda x: re.sub(r'http\S+', '', x))

test['clean_tweet'] = test['tweet'].apply(lambda x: re.sub(r'http\S+', '', x))

In [9]:
punctuation = '!"#$%&()*+-/:;<=>?@[\\]^_`{|}~.,'

train['clean_tweet'] = train['clean_tweet'].apply(lambda x: ''.join(ch for ch in x if ch not in set(punctuation)))
test['clean_tweet'] = test['clean_tweet'].apply(lambda x: ''.join(ch for ch in x if ch not in set(punctuation)))

In [10]:
# convert text to lowercase
train['clean_tweet'] = train['clean_tweet'].str.lower()
test['clean_tweet'] = test['clean_tweet'].str.lower()

In [11]:
# remove numbers
train['clean_tweet'] = train['clean_tweet'].str.replace("[0-9]", " ")
test['clean_tweet'] = test['clean_tweet'].str.replace("[0-9]", " ")

In [12]:
# remove whitespaces
train['clean_tweet'] = train['clean_tweet'].apply(lambda x:' '.join(x.split()))
test['clean_tweet'] = test['clean_tweet'].apply(lambda x: ' '.join(x.split()))

In [13]:
 # Function which directly tokenize the tweet data
import nltk
from nltk.tokenize import TweetTokenizer

tt = TweetTokenizer()
train['clean_tweet'].apply(tt.tokenize)

0       [fingerprint, pregnancy, test, android, apps, ...
1       [finally, a, transparant, silicon, case, thank...
2       [we, love, this, would, you, go, talk, makemem...
3       [i'm, wired, i, know, i'm, george, i, was, mad...
4       [what, amazing, service, apple, won't, even, t...
5       [iphone, software, update, fucked, up, my, pho...
6       [happy, for, us, instapic, instadaily, us, son...
7       [new, type, c, charger, cable, uk, â€¦, bay, ama...
8       [bout, to, go, shopping, again, listening, to,...
9       [photo, fun, selfie, pool, water, sony, camera...
10      [hey, apple, when, you, make, a, new, ipod, do...
11      [ha, not, heavy, machinery, but, it, does, wha...
12      [contemplating, giving, in, to, the, iphone, b...
13      [i, just, made, another, crazy, purchase, lol,...
14      [shaqlockholmes, samlouise, the, battery, is, ...
15      [from, deepellum, towards, downtown, dallas, b...
16      [like, and, share, if, you, want, this, d, pho...
17      [go, crazy, iphonesia, iphone, instagood, inst...
18      [the, reason, i, don't, have, one, iphone, suc...
19      [how, is, the, apple, store, gunna, be, out, o...
20      [apple, art, easter, dear, friends, if, you, w...
21      [excuse, me, waiter, there, seems, to, be, a, ...
22      [i've, had, this, new, ipod, for, four, days, ...
23      [when, your, iphone, screen, goes, completely,...
24      [it's, time, for, new, wallpapers, phone, wall...
25      [billion, for, patents, where, there, is, prio...
26      [my, ipod, is, all, messed, up, and, i, haven'...
27      [my, ipod, touch, is, frozen, on, the, apple, ...
28      [do, love, a, new, phone, case, flower, green,...
29      [must, watch, youtube, subscribe, daily, vlog,...
                              ...
7890    [okay, i, upgraded, my, phone, to, an, iphone,...
7891    [new, dress, thanks, to, momma, apple, dress, ...
7892    [love, recording, videos, for, you, guys, amaz...
7893    [happy, birthday, to, me, thank, you, daddy, b...
7894    [blue, skys, nothin, but, blue, skies, metroma...
7895    [khalsir, same, here, have, to, fork, out, Â£, ...
7896    [so, pissed, macbook, crashes, apple, company,...
7897    [slowly, moving, away, from, shitty, apple, go...
7898    [we, would, like, to, wish, you, an, amazing, ...
7899    [early, christmas, present, sure, dont, mind, ...
7900    [why, did, my, iphone, calendar, link, with, m...
7901    [brendanbrady, the, new, apple, advert, can, f...
7902    [all, i, wanna, do, is, put, music, from, my, ...
7903    [kaylahinks, snapchatprobbz, haha, so, true, d...
7904    [fuckyou, apple, one, thing, stops, working, a...
7905    [ove, a, fist, inside, my, oh, god, i, a, fist...
7906    [legit, feels, like, i, have, a, brand, new, p...
7907    [tipsy, rhymes, with, e, ye, we, je, mi, ne, d...
7908    [second, fucking, time, stay, on, hold, for, m...
7909    [rt, monteithelgort, first, post, from, my, ne...
7910    [perfect, match, instagood, applewatch, red, i...
7911    [i, am, completely, in, love, with, the, new, ...
7912    [tune, in, turn, on, drop, out, gtd, in, one, ...
7913    [ok, so, my, galaxy, crashed, after, one, day,...
7914    [gain, followers, rt, this, must, follow, me, ...
7915    [live, out, loud, lol, liveoutloud, selfie, sm...
7916    [we, would, like, to, wish, you, an, amazing, ...
7917    [helping, my, lovely, year, old, neighbor, wit...
7918    [finally, got, my, smart, pocket, wifi, stay, ...
7919    [apple, barcelona, apple, store, bcn, barcelon...
Name: clean_tweet, Length: 7920, dtype: object

In [14]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Ananta
[nltk_data]     Arora\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [15]:
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize

ps = PorterStemmer()

In [16]:
def tokenize(text):
    return word_tokenize(text)

def stemming(words):
    stem_words = []
    for w in words:
        w = ps.stem(w)
        stem_words.append(w)
    
    return stem_words

In [17]:
train.head(5)

,id,label,tweet,clean_tweet
0,1,0,#fingerprint #Pregnancy Test https://goo.gl/h1...,fingerprint pregnancy test android apps beauti...
1,2,0,Finally a transparant silicon case ^^ Thanks t...,finally a transparant silicon case thanks to m...
2,3,0,We love this! Would you go? #talk #makememorie...,we love this would you go talk makememories un...
3,4,0,I'm wired I know I'm George I was made that wa...,i'm wired i know i'm george i was made that wa...
4,5,1,What amazing service! Apple won't even talk to...,what amazing service apple won't even talk to ...

In [18]:
train.drop(['tweet'], axis = 1, inplace=True)

In [19]:
# apply tokenize function
train['text'] = train['clean_tweet'].apply(tokenize)

In [20]:
# apply steming function
train['tokenized'] = train['text'].apply(stemming)

In [21]:
train.head()

,id,label,clean_tweet,text,tokenized
0,1,0,fingerprint pregnancy test android apps beauti...,"[fingerprint, pregnancy, test, android, apps, ...","[fingerprint, pregnanc, test, android, app, be..."
1,2,0,finally a transparant silicon case thanks to m...,"[finally, a, transparant, silicon, case, thank...","[final, a, transpar, silicon, case, thank, to,..."
2,3,0,we love this would you go talk makememories un...,"[we, love, this, would, you, go, talk, makemem...","[we, love, thi, would, you, go, talk, makememo..."
3,4,0,i'm wired i know i'm george i was made that wa...,"[i, 'm, wired, i, know, i, 'm, george, i, was,...","[i, 'm, wire, i, know, i, 'm, georg, i, wa, ma..."
4,5,1,what amazing service apple won't even talk to ...,"[what, amazing, service, apple, wo, n't, even,...","[what, amaz, servic, appl, wo, n't, even, talk..."

### Wordlist

In [22]:
from collections import Counter
words = Counter()
for idx in train.index:
    words.update(train.loc[idx, "text"])

words.most_common(5)

[('iphone', 4128), ('apple', 2863), ('i', 2455), ('my', 2274), ('the', 2009)]

In [23]:
nltk.download('stopwords')
stopwords=nltk.corpus.stopwords.words("english")

[nltk_data] Downloading package stopwords to C:\Users\Ananta
[nltk_data]     Arora\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

#### Removing stop words

In [24]:
whitelist = ["n't", "not"]
for idx, stop_word in enumerate(stopwords):
    if stop_word not in whitelist:
        del words[stop_word]
words.most_common(5)

[('iphone', 4128),
 ('apple', 2863),
 ('samsung', 1390),
 ('new', 1137),
 ('phone', 951)]

In [25]:
def word_list(processed_data):
    #print(processed_data)
    min_occurrences=3 
    max_occurences=500 
    stopwords=nltk.corpus.stopwords.words("english")
    whitelist = ["n't","not"]
    wordlist = []
    
    whitelist = whitelist if whitelist is None else whitelist
    
    words = Counter()
    for idx in processed_data.index:
        words.update(processed_data.loc[idx, "text"])

    for idx, stop_word in enumerate(stopwords):
        if stop_word not in whitelist:
            del words[stop_word]
    #print(words)

    word_df = pd.DataFrame(data={"word": [k for k, v in words.most_common() if min_occurrences < v < max_occurences],
                                 "occurrences": [v for k, v in words.most_common() if min_occurrences < v < max_occurences]},
                           columns=["word", "occurrences"])
    #print(word_df)
    word_df.to_csv("wordlist.csv", index_label="idx")
    wordlist = [k for k, v in words.most_common() if min_occurrences < v < max_occurences]
    #print(wordlist)

In [26]:
word_list(train)

In [27]:
words = pd.read_csv(r"C:\Users\Ananta Arora\Documents\Python Programming\wordlist.csv")

### Bag of words

In [28]:
import os

In [29]:
wordlist= []
if os.path.isfile("wordlist.csv"):
    word_df = pd.read_csv("wordlist.csv")
    word_df = word_df[word_df["occurrences"] > 3]
    wordlist = list(word_df.loc[:, "word"])

label_column = ["label"]
columns = label_column + list(map(lambda w: w + "_bow",wordlist))
labels = []
rows = []
for idx in train.index:
    current_row = []
    
    # add label
    current_label = train.loc[idx, "label"]
    labels.append(current_label)
    current_row.append(current_label)

    # add bag-of-words
    tokens = set(train.loc[idx, "text"])
    for _, word in enumerate(wordlist):
        current_row.append(1 if word in tokens else 0)

    rows.append(current_row)

data_model = pd.DataFrame(rows, columns=columns)
data_labels = pd.Series(labels)


bow = data_model

print(bow)

      label  love_bow  life_bow  android_bow  ios_bow  rt_bow  day_bow  \
0         0         0         0            1        0       0        0
1         0         0         0            0        0       0        0
2         0         1         0            0        0       0        0
3         0         0         0            0        0       0        0
4         1         0         0            0        0       0        0
5         1         0         0            0        0       0        0
6         0         0         0            0        0       0        0
7         0         0         0            0        0       0        0
8         0         0         0            0        0       0        0
9         0         0         0            0        0       0        0
10        1         0         0            0        0       0        0
11        1         0         0            0        0       0        0
12        1         0         0            0        0       0        0
13        0         0         0            0        0       0        0
14        1         0         0            0        0       0        0
15        0         0         0            0        0       0        0
16        0         0         0            0        0       0        0
17        0         0         0            0        0       0        0
18        1         0         0            0        0       0        0
19        1         0         0            0        0       0        0
20        0         0         0            0        0       0        0
21        0         0         0            0        0       0        0
22        1         0         0            0        0       0        0
23        1         0         0            0        0       0        1
24        0         0         0            0        0       0        0
25        0         0         0            0        0       0        0
26        1         0         0            0        0       0        0
27        1         0         0            0        0       0        0
28        0         1         0            0        0       0        0
29        0         0         0            1        1       0        0
...     ...       ...       ...          ...      ...     ...      ...
7890      1         0         0            0        0       0        0
7891      0         0         0            0        0       0        0
7892      0         1         0            0        0       0        0
7893      0         0         0            0        0       0        0
7894      0         0         0            0        0       0        0
7895      1         0         0            0        0       0        0
7896      1         0         0            0        0       0        0
7897      1         0         0            0        0       0        0
7898      0         0         1            0        0       0        1
7899      0         0         0            0        0       0        0
7900      0         0         0            0        0       0        0
7901      1         0         0            0        0       0        0
7902      1         0         0            0        0       0        0
7903      0         0         0            0        0       0        0
7904      1         0         0            0        0       0        0
7905      0         0         0            0        0       0        0
7906      0         0         0            0        0       0        0
7907      0         0         0            0        0       0        0
7908      1         0         0            0        0       0        0
7909      0         0         0            0        0       1        0
7910      0         0         0            0        0       0        0
7911      0         1         0            0        0       0        0
7912      0         0         0            0        0       0        0
7913      1         0         0            0        0       0        1
7914      0         0         0            0        0       1        0
7915      0         0         0            0        0       0        0
7916      0         0         1            0        0       0        1
7917      0         0         0            0        0       0        0
7918      0         0         0            0        0       0        0
7919      0         0         0            0        0       0        0

      instagram_bow  not_bow  cute_bow  ...  items_bow  healthyeating_bow  \
0                 0        0         1  ...          0                  0
1                 0        0         0  ...          0                  0
2                 0        0         0  ...          0                  0
3                 0        0         1  ...          0                  0
4                 0        0         0  ...          0                  0
5                 0        0         0  ...          0                  0
6                 0        0         0  ...          0                  0
7                 0        0         0  ...          0                  0
8                 0        0         0  ...          0                  0
9                 0        0         1  ...          0                  0
10                0        1         0  ...          0                  0
11                0        1         0  ...          0                  0
12                0        0         0  ...          0                  0
13                0        0         0  ...          0                  0
14                0        0         0  ...          0                  0
15                0        0         0  ...          0                  0
16                0        0         0  ...          0                  0
17                1        0         0  ...          0                  0
18                0        0         0  ...          0                  0
19                0        0         0  ...          0                  0
20                0        0         0  ...          0                  0
21                0        0         0  ...          0                  0
22                0        0         0  ...          0                  0
23                0        0         0  ...          0                  0
24                0        0         0  ...          0                  0
25                0        0         0  ...          0                  0
26                0        0         0  ...          0                  0
27                0        0         0  ...          0                  0
28                0        0         1  ...          0                  0
29                0        0         0  ...          0                  0
...             ...      ...       ...  ...        ...                ...
7890              0        0         0  ...          0                  0
7891              0        0         1  ...          0                  0
7892              0        0         0  ...          0                  0
7893              0        0         0  ...          0                  0
7894              0        0         0  ...          0                  0
7895              0        0         0  ...          0                  0
7896              0        0         0  ...          0                  0
7897              0        0         0  ...          0                  0
7898              0        0         0  ...          0                  0
7899              0        0         0  ...          0                  0
7900              0        0         0  ...          0                  0
7901              0        0         0  ...          0                  0
7902              0        0         0  ...          0                  0
7903              0        0         0  ...          0                  0
7904              0        0         0  ...          0                  0
7905              0        0         0  ...          0                  0
7906              0        0         0  ...          0                  0
7907              0        0         0  ...          0                  0
7908              0        0         0  ...          0                  0
7909              0        0         0  ...          0                  0
7910              1        0         0  ...          0                  0
7911              0        0         0  ...          0                  0
7912              0        0         0  ...          0                  0
7913              0        0         0  ...          0                  0
7914              0        0         0  ...          0                  0
7915              0        0         0  ...          0                  0
7916              0        0         0  ...          0                  0
7917              0        0         0  ...          0                  0
7918              0        0         0  ...          0                  0
7919              0        0         0  ...          0                  0

      hung_bow  kushking_bow  roadtrip_bow  feedback_bow  knew_bow  ee_bow  \
0            0             0             0             0         0       0
1            0             0             0             0         0       0
2            0             0             0             0         0       0
3            0             0             0             0         0       0
4            0             0             0             0         0       0
5            0             0             0             0         0       0
6            0             0             0             0         0       0
7            0             0             0             0         0       0
8            0             0             0             0         0       0
9            0             0             0             0         0       0
10           0             0             0             0         0       0
11           0             0             0             0         0       0
12           0             0             0             0         0       0
13           0             0             0             0         0       0
14           0             0             0             0         0       0
15           0             0             0             0         0       0
16           0             0             0             0         0       0
17           0             0             0             0         0       0
18           0             0             0             0         0       0
19           0             0             0             0         0       0
20           0             0             0             0         0       0
21           0             0             0             0         0       0
22           0             0             0             0         0       0
23           0             0             0             0         0       0
24           0             0             0             0         0       0
25           0             0             0             0         0       0
26           0             0             0             0         0       0
27           0             0             0             0         0       0
28           0             0             0             0         0       0
29           0             0             0             0         0       0
...        ...           ...           ...           ...       ...     ...
7890         0             0             0             0         0       0
7891         0             0             0             0         0       0
7892         0             0             0             0         0       0
7893         0             0             0             0         0       0
7894         0             0             0             0         0       0
7895         0             0             0             0         0       0
7896         0             0             0             0         0       0
7897         0             0             0             0         0       0
7898         0             0             0             0         0       0
7899         0             0             0             0         0       0
7900         0             0             0             0         0       0
7901         0             0             0             0         0       0
7902         0             0             0             0         0       0
7903         0             0             0             0         0       0
7904         0             0             0             0         0       0
7905         0             0             0             0         0       0
7906         0             0             0             0         0       0
7907         0             0             0             0         0       0
7908         0             0             0             0         0       0
7909         0             0             0             0         0       0
7910         0             0             0             0         0       0
7911         0             0             0             0         0       0
7912         0             0             0             0         0       0
7913         0             0             0             0         0       0
7914         0             0             0             0         0       0
7915         0             0             0             0         0       0
7916         0             0             0             0         0       0
7917         0             0             0             0         0       0
7918         0             0             0             0         0       0
7919         0             0             0             0         0       0

      growing_bow  vw_bow
0               0       0
1               0       0
2               0       0
3               0       0
4               0       0
5               0       0
6               0       0
7               0       0
8               0       0
9               0       0
10              0       0
11              0       0
12              0       0
13              0       0
14              0       0
15              0       0
16              0       0
17              0       0
18              0       0
19              0       0
20              0       0
21              0       0
22              0       0
23              0       0
24              0       0
25              0       0
26              0       0
27              0       0
28              0       0
29              0       0
...           ...     ...
7890            0       0
7891            0       0
7892            0       0
7893            0       0
7894            0       0
7895            0       0
7896            0       0
7897            0       0
7898            0       0
7899            0       0
7900            0       0
7901            0       0
7902            0       0
7903            0       0
7904            0       0
7905            0       0
7906            0       0
7907            0       0
7908            0       0
7909            0       0
7910            0       0
7911            0       0
7912            0       0
7913            0       0
7914            0       0
7915            0       0
7916            0       0
7917            0       0
7918            0       0
7919            0       0

[7920 rows x 2949 columns]

## Classification

In [30]:
import random
seed = 777
random.seed(seed)

In [31]:
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score

def test_classifier(X_train, y_train, X_test, y_test, classifier):
    log("")
    log("---------------------------------------------------------")
    log("Testing " + str(type(classifier).__name__))
    now = time()
    list_of_labels = sorted(list(set(y_train)))
    model = classifier.fit(X_train, y_train)
    log("Learing time {0}s".format(time() - now))
    now = time()
    predictions = model.predict(X_test)
    log("Predicting time {0}s".format(time() - now))
    
    # Calculate Accuracy, Precision, recall
    
    precision = precision_score(y_test, predictions, average=None, pos_label=None, labels=list_of_labels)
    recall = recall_score(y_test, predictions, average=None, pos_label=None, labels=list_of_labels)
    accuracy = accuracy_score(y_test, predictions)
    f1 = f1_score(y_test, predictions, average=None, pos_label=None, labels=list_of_labels)
    
    log("=================== Results ===================")
    log("            Negative       Positive")
    log("F1       " + str(f1))
    log("Precision" + str(precision))
    log("Recall   " + str(recall))
    log("Accuracy " + str(accuracy))
    log("===============================================")

    return precision, recall, accuracy, f1

def log(x):
    #can be used to write to log file
    print(x)

In [32]:
from time import time
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, RandomizedSearchCV

from sklearn.naive_bayes import BernoulliNB
X_train, X_test, y_train, y_test = train_test_split(bow.iloc[:, 1:], bow['label'], test_size=0.3)
precision, recall, accuracy, f1 = test_classifier(X_train, y_train, X_test, y_test, BernoulliNB())

---------------------------------------------------------
Testing BernoulliNB
Learing time 0.44281792640686035s
Predicting time 0.15657925605773926s
=================== Results ===================
            Negative       Positive
F1       [0.91107185 0.77728614]
Precision[0.95967742 0.68979058]
Recall   [0.86715247 0.8902027 ]
Accuracy 0.872895622895623
===============================================

In [33]:
def cv(classifier, X_train, y_train):
    log("===============================================")
    classifier_name = str(type(classifier).__name__)
    now = time()
    log("Crossvalidating " + classifier_name + "...")
    accuracy = [cross_val_score(classifier, X_train, y_train, cv=8, n_jobs=-1)]
    log("Crosvalidation completed in {0}s".format(time() - now))
    log("Accuracy: " + str(accuracy[0]))
    log("Average accuracy: " + str(np.array(accuracy[0]).mean()))
    log("===============================================")
    return accuracy

acc_train = cv(BernoulliNB(), X_train, y_train)
print("training acc",acc_train)

acc_test = cv(BernoulliNB(), X_test, y_test)
print("testing acc",acc_test)

===============================================
Crossvalidating BernoulliNB...
Crosvalidation completed in 5.472558975219727s
Accuracy: [0.86023055 0.870317   0.86724387 0.89033189 0.87012987 0.87012987
 0.88294798 0.89884393]
Average accuracy: 0.8762718694727781
===============================================
training acc [array([0.86023055, 0.870317  , 0.86724387, 0.89033189, 0.87012987,
       0.87012987, 0.88294798, 0.89884393])]
===============================================
Crossvalidating BernoulliNB...
Crosvalidation completed in 4.0624754428863525s
Accuracy: [0.88215488 0.88215488 0.86195286 0.87542088 0.83164983 0.88888889
 0.85185185 0.89225589]
Average accuracy: 0.8707912457912458
===============================================
testing acc [array([0.88215488, 0.88215488, 0.86195286, 0.87542088, 0.83164983,
       0.88888889, 0.85185185, 0.89225589])]

In [109]:
clf = BernoulliNB(alpha=.01)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)
p = pred[:1953]

In [35]:
print(X_test)

      love_bow  life_bow  android_bow  ios_bow  rt_bow  day_bow  \
7450         0         0            0        1       0        0
1351         0         0            0        0       0        0
2291         0         0            0        0       0        0
1654         0         0            0        0       0        0
4294         0         0            0        0       0        0
5865         0         0            0        1       0        0
7278         1         0            0        0       0        0
649          0         0            0        0       0        0
3107         1         0            0        0       0        0
7489         0         0            0        0       0        0
5192         0         0            0        0       0        1
3421         0         0            0        0       0        0
7739         0         0            0        0       0        0
6829         0         0            0        0       0        0
2730         0         0            0        0       0        0
1943         0         0            0        0       1        0
3575         0         0            0        0       0        0
3140         0         0            0        0       0        0
7564         0         0            0        0       0        0
941          1         0            0        0       0        0
411          0         0            0        0       0        0
4337         0         0            0        0       0        0
4157         0         0            0        0       0        1
6565         0         0            0        0       0        0
2827         0         0            0        0       0        0
4004         0         0            0        0       0        0
1716         0         0            0        0       0        0
4706         0         0            0        0       0        0
4720         0         0            0        0       0        0
1884         0         0            0        0       0        0
...        ...       ...          ...      ...     ...      ...
2163         0         0            0        0       0        0
5828         0         0            0        0       0        0
1800         0         0            1        0       0        0
3534         0         0            0        0       0        0
455          0         1            0        0       0        0
3941         0         0            0        1       0        0
2345         0         0            0        0       0        0
1538         0         0            0        0       0        0
1267         0         0            0        0       0        0
2516         0         0            0        0       0        0
6476         0         0            1        0       0        0
7436         1         0            0        0       0        0
3810         0         0            0        0       0        0
6963         0         0            0        0       0        0
153          1         0            0        0       0        0
1360         0         0            0        0       0        0
4481         0         0            0        0       0        0
6254         0         0            0        0       0        0
6788         0         0            0        0       0        0
2108         0         0            0        0       0        0
2593         0         0            0        0       0        1
2465         0         0            0        0       0        0
3937         1         0            0        0       0        0
4495         0         0            0        0       0        0
2970         0         0            1        0       0        0
6065         0         0            0        0       0        0
6609         0         0            0        0       0        0
5543         0         0            0        0       0        0
2007         0         0            0        0       0        1
2470         0         0            0        0       0        0

      instagram_bow  not_bow  cute_bow  photo_bow  ...  items_bow  \
7450              0        0         0          0  ...          0
1351              1        0         0          0  ...          0
2291              0        0         0          0  ...          0
1654              0        0         0          0  ...          0
4294              0        0         0          0  ...          0
5865              0        0         0          0  ...          0
7278              0        0         0          0  ...          0
649               0        0         0          0  ...          0
3107              0        0         0          0  ...          0
7489              0        0         0          0  ...          0
5192              0        0         0          0  ...          0
3421              0        0         0          0  ...          0
7739              0        0         0          0  ...          0
6829              0        0         0          0  ...          0
2730              0        0         0          0  ...          0
1943              0        0         0          0  ...          0
3575              0        0         0          0  ...          0
3140              0        0         0          0  ...          0
7564              0        0         0          0  ...          0
941               0        0         0          0  ...          0
411               0        0         0          0  ...          0
4337              0        0         0          0  ...          0
4157              0        0         0          0  ...          0
6565              0        0         0          0  ...          0
2827              0        0         0          0  ...          0
4004              0        0         0          0  ...          0
1716              0        0         0          0  ...          0
4706              0        0         0          0  ...          0
4720              0        0         0          0  ...          0
1884              1        0         0          0  ...          0
...             ...      ...       ...        ...  ...        ...
2163              0        0         0          0  ...          0
5828              0        0         0          0  ...          0
1800              0        0         0          0  ...          0
3534              0        1         0          0  ...          0
455               0        0         0          0  ...          0
3941              0        0         0          0  ...          0
2345              0        0         0          0  ...          0
1538              0        0         0          0  ...          0
1267              0        0         0          0  ...          0
2516              1        0         0          0  ...          0
6476              0        0         1          0  ...          0
7436              0        0         0          0  ...          0
3810              0        0         0          0  ...          0
6963              0        0         0          0  ...          0
153               0        0         0          0  ...          0
1360              0        0         0          0  ...          0
4481              0        0         0          0  ...          0
6254              0        1         0          1  ...          0
6788              0        0         0          0  ...          0
2108              0        0         0          0  ...          0
2593              0        0         0          0  ...          0
2465              0        0         0          0  ...          0
3937              0        0         0          0  ...          0
4495              0        0         0          0  ...          0
2970              0        0         0          0  ...          0
6065              0        0         0          0  ...          0
6609              0        0         0          0  ...          0
5543              0        0         0          0  ...          0
2007              1        0         0          0  ...          0
2470              0        0         0          0  ...          0

      healthyeating_bow  hung_bow  kushking_bow  roadtrip_bow  feedback_bow  \
7450                  0         0             0             0             0
1351                  0         0             0             0             0
2291                  0         0             0             0             0
1654                  0         0             0             0             0
4294                  0         0             0             0             0
5865                  0         0             0             0             0
7278                  0         0             0             0             0
649                   0         0             0             0             0
3107                  0         0             0             0             0
7489                  0         0             0             0             0
5192                  0         0             0             0             0
3421                  0         0             0             0             0
7739                  0         0             0             0             0
6829                  0         0             0             0             0
2730                  0         0             0             0             0
1943                  0         0             0             0             0
3575                  0         0             0             0             0
3140                  0         0             0             0             0
7564                  0         0             0             0             0
941                   0         0             0             0             0
411                   0         0             0             0             0
4337                  0         0             0             0             0
4157                  0         0             0             0             0
6565                  0         0             0             0             0
2827                  0         0             0             0             0
4004                  0         0             0             0             0
1716                  0         0             0             0             0
4706                  0         0             0             0             0
4720                  0         0             0             0             0
1884                  0         0             0             0             0
...                 ...       ...           ...           ...           ...
2163                  0         0             0             0             0
5828                  0         0             0             0             0
1800                  0         0             0             0             0
3534                  0         0             0             0             0
455                   0         0             0             0             0
3941                  0         0             0             0             0
2345                  0         0             0             0             0
1538                  0         0             0             0             0
1267                  0         0             0             0             0
2516                  0         0             0             0             0
6476                  0         0             0             0             0
7436                  0         0             0             0             0
3810                  0         0             0             0             0
6963                  0         0             0             0             0
153                   0         0             0             0             0
1360                  0         0             0             0             0
4481                  0         0             0             0             0
6254                  0         0             0             0             0
6788                  0         0             0             0             0
2108                  0         0             0             0             0
2593                  0         0             0             0             0
2465                  0         0             0             0             0
3937                  0         0             0             0             0
4495                  0         0             0             0             0
2970                  0         0             0             0             0
6065                  0         0             0             0             0
6609                  0         0             0             0             0
5543                  0         0             0             0             0
2007                  0         0             0             0             0
2470                  0         0             0             0             0

      knew_bow  ee_bow  growing_bow  vw_bow
7450         0       0            0       0
1351         0       0            0       0
2291         0       0            0       0
1654         0       0            0       0
4294         0       0            0       0
5865         0       0            0       0
7278         0       0            0       0
649          0       0            0       0
3107         0       0            0       0
7489         0       0            0       0
5192         0       0            0       0
3421         0       0            0       0
7739         0       0            0       0
6829         0       0            0       0
2730         0       0            0       0
1943         0       0            0       0
3575         0       0            0       0
3140         0       0            0       0
7564         0       0            0       0
941          0       0            0       0
411          0       0            0       0
4337         0       0            0       0
4157         0       0            0       0
6565         0       0            0       0
2827         0       0            0       0
4004         0       0            0       0
1716         0       0            0       0
4706         0       0            0       0
4720         0       0            0       0
1884         0       0            0       0
...        ...     ...          ...     ...
2163         0       0            0       0
5828         0       0            0       0
1800         0       0            0       0
3534         0       0            0       0
455          0       0            0       0
3941         0       0            0       0
2345         0       0            0       0
1538         0       0            0       0
1267         0       0            0       0
2516         0       0            0       0
6476         0       0            0       0
7436         0       0            0       0
3810         0       0            0       0
6963         0       0            0       0
153          0       0            0       0
1360         0       0            0       0
4481         0       0            0       0
6254         0       0            0       0
6788         0       0            0       0
2108         0       0            0       0
2593         0       0            0       0
2465         0       0            0       0
3937         0       0            0       0
4495         0       0            0       0
2970         0       0            0       0
6065         0       0            0       0
6609         0       0            0       0
5543         0       0            0       0
2007         0       0            0       0
2470         0       0            0       0

[2376 rows x 2948 columns]

In [36]:
print(y_test)

7450    0
1351    0
2291    0
1654    1
4294    0
5865    1
7278    0
649     0
3107    0
7489    1
5192    0
3421    0
7739    1
6829    0
2730    1
1943    0
3575    1
3140    1
7564    1
941     0
411     0
4337    0
4157    0
6565    0
2827    0
4004    0
1716    0
4706    0
4720    0
1884    0
       ..
2163    0
5828    0
1800    1
3534    0
455     0
3941    1
2345    0
1538    0
1267    1
2516    0
6476    0
7436    0
3810    1
6963    0
153     0
1360    0
4481    0
6254    0
6788    1
2108    1
2593    0
2465    0
3937    0
4495    0
2970    0
6065    1
6609    0
5543    0
2007    0
2470    0
Name: label, Length: 2376, dtype: int64

### Using xgboost

In [37]:
from xgboost import XGBClassifier as XGBoostClassifier

In [38]:
X_train, X_test, y_train, y_test = train_test_split(data_model.drop(columns='label',axis=1),data_model['label'] , test_size=0.3)
precision, recall, accuracy, f1 = test_classifier(X_train, y_train, X_test, y_test, XGBoostClassifier(seed=seed))

---------------------------------------------------------
Testing XGBClassifier
Learing time 45.269227743148804s
Predicting time 0.2975778579711914s
=================== Results ===================
            Negative       Positive
F1       [0.88605659 0.46079614]
Precision[0.81063433 0.82327586]
Recall   [0.97695334 0.319933  ]
Accuracy 0.8118686868686869
===============================================

### Using SVM

In [39]:
#Using Support Vector Machine
from sklearn.svm import SVC

In [40]:
X_train, X_test, y_train, y_test = train_test_split(data_model.drop(columns='label',axis=1),data_model['label'] , test_size=0.3)
precision, recall, accuracy, f1 = test_classifier(X_train, y_train, X_test, y_test, SVC())

---------------------------------------------------------
Testing SVC

c:\users\ananta arora\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

Learing time 54.16150665283203s
Predicting time 22.140917539596558s
=================== Results ===================
            Negative       Positive
F1       [0.85714286 0.        ]
Precision[0.75 0.  ]
Recall   [1. 0.]
Accuracy 0.75
===============================================

c:\users\ananta arora\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\ananta arora\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [53]:
dat1 = test
dat2 = data_model

dat1 = dat1.reset_index(drop=True)
dat2 = dat2.reset_index(drop=True)

In [54]:
dat1.head(5)

,id,tweet,clean_tweet
0,7921,I hate the new #iphone upgrade. Won't let me d...,i hate the new iphone upgrade won't let me dow...
1,7922,currently shitting my fucking pants. #apple #i...,currently shitting my fucking pants apple imac...
2,7923,"I'd like to puts some CD-ROMS on my iPad, is t...",i'd like to puts some cdroms on my ipad is tha...
3,7924,My ipod is officially dead. I lost all my pict...,my ipod is officially dead i lost all my pictu...
4,7925,Been fighting iTunes all night! I only want th...,been fighting itunes all night i only want the...

In [55]:
dat2.head(5)

,id,tweet,clean_tweet,label,love_bow,life_bow,android_bow,ios_bow,rt_bow,day_bow,...,items_bow,healthyeating_bow,hung_bow,kushking_bow,roadtrip_bow,feedback_bow,knew_bow,ee_bow,growing_bow,vw_bow
0,7921,I hate the new #iphone upgrade. Won't let me d...,i hate the new iphone upgrade won't let me dow...,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7922,currently shitting my fucking pants. #apple #i...,currently shitting my fucking pants apple imac...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,7923,"I'd like to puts some CD-ROMS on my iPad, is t...",i'd like to puts some cdroms on my ipad is tha...,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,7924,My ipod is officially dead. I lost all my pict...,my ipod is officially dead i lost all my pictu...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,7925,Been fighting iTunes all night! I only want th...,been fighting itunes all night i only want the...,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [58]:
dat2 = dat2.drop(columns=['tweet','clean_tweet','id'], axis=1)

In [59]:
data_model = dat1.join(dat2)

In [81]:
data_model.head(5)

,id,tweet,clean_tweet,label,love_bow,life_bow,android_bow,ios_bow,rt_bow,day_bow,...,items_bow,healthyeating_bow,hung_bow,kushking_bow,roadtrip_bow,feedback_bow,knew_bow,ee_bow,growing_bow,vw_bow
0,7921,I hate the new #iphone upgrade. Won't let me d...,i hate the new iphone upgrade won't let me dow...,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7922,currently shitting my fucking pants. #apple #i...,currently shitting my fucking pants apple imac...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,7923,"I'd like to puts some CD-ROMS on my iPad, is t...",i'd like to puts some cdroms on my ipad is tha...,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,7924,My ipod is officially dead. I lost all my pict...,my ipod is officially dead i lost all my pictu...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,7925,Been fighting iTunes all night! I only want th...,been fighting itunes all night i only want the...,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [62]:
test_model = pd.DataFrame()
test_model['original_id'] = data_model['id']

In [84]:
test_model.sample

<bound method NDFrame.sample of       original_id
0            7921
1            7922
2            7923
3            7924
4            7925
5            7926
6            7927
7            7928
8            7929
9            7930
10           7931
11           7932
12           7933
13           7934
14           7935
15           7936
16           7937
17           7938
18           7939
19           7940
20           7941
21           7942
22           7943
23           7944
24           7945
25           7946
26           7947
27           7948
28           7949
29           7950
...           ...
1923         9844
1924         9845
1925         9846
1926         9847
1927         9848
1928         9849
1929         9850
1930         9851
1931         9852
1932         9853
1933         9854
1934         9855
1935         9856
1936         9857
1937         9858
1938         9859
1939         9860
1940         9861
1941         9862
1942         9863
1943         9864
1944         9865
1945         9866
1946         9867
1947         9868
1948         9869
1949         9870
1950         9871
1951         9872
1952         9873

[1953 rows x 1 columns]>

In [95]:
test_model.index

RangeIndex(start=0, stop=1953, step=1)

In [110]:
results = pd.DataFrame([],columns=["Id","Category"])
results["Id"] = test_model["original_id"].astype("float64")
results["Category"] = p
results.to_csv("results_xgb.csv",index=False)